apiVersion: v1
kind: Service
metadata:
  name: sample-fastapi
  namespace: sample-fastapi
  labels:
    app.kubernetes.io/name: sample-fastapi
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sample-fastapi
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
