apiVersion: v1
kind: Service
metadata:
  name: sample-worker-metrics
  namespace: sample-fastapi
  labels:
    app.kubernetes.io/name: sample-fastapi
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sample-fastapi
    app.kubernetes.io/component: worker
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
