# alb의 기본 target은 instance인데 해당 부분을 ip로 바꾸는 부분
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: my-app-tg-config
  namespace: default
spec:
  targetReference:
    group: ""
    kind: Service
    name: my-app-service
  defaultConfiguration:
    targetType: ip           
    protocol: HTTP
    protocolVersion: HTTP1