{{- if not .Values.telegram.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finops.fullname" . }}-telegram
  labels:
    {{- include "finops.labels" . | nindent 4 }}
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.botToken | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.telegram.chatId | quote }}
{{- end }}
