replicaCount: 1

image:
  # Replace with your container registry URI where the image is pushed
  repository: <YOUR_REGISTRY>/finops-analyzer
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

env:
  # Set mock mode to false for real KRR execution
  MOCK_INTEGRATION: "false"
  PROMETHEUS_URL: "http://prometheus-stack-kube-prom-prometheus.prometheus.svc.cluster.local:9090"
  CHRONOS_URL: "http://chronos-model.monitoring.svc.cluster.local:8000"
  TELEGRAM_BOT_TOKEN: "8818476894:AAEEIiJvfmTBK5zNpF0_sv12DZmwz17k6kc"
  TELEGRAM_CHAT_ID: "8753092843"
  AUTO_SEND_TELEGRAM: "true"

cronjob:
  enabled: true
  schedule: "0 3 * * *"  # 매일 새벽 3시 (Cron 표현식: 새벽 3시 0분)
  targetDeployment: "sample-fastapi"
  targetNamespace: "sample-fastapi"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi
